# Generated by Django 5.1.1 on 2025-11-19 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.role'),
        ),
    ]
